Wands:
  EmpireWand:
    Enabled: true
    UseCustomSpellSet: false
    Spells:
  BloodWand:
    Enabled: true
    UseCustomSpellSet: false
    Spells:
  CelestialWand:
    Enabled: true
    UseCustomSpellSet: false
    Spells:
  ScytheWand:
    Enabled: true
    UseCustomSpellSet: false
    Spells:
  HellWand:
    Enabled: true
    UseCustomSpellSet: false
    Spells:

Spells:
  Blood Cloud:
    Enabled: true
  Blood Spark:
    Enabled: true
    Range: 25
  Blood Wave:
    Enabled: true
  Capture:
    Enabled: true
    Range: 25
  Celestial Cloud:
    Enabled: true
  Celestial Confuse:
    Enabled: true
    Range: 25
  Celestial Stun:
    Enabled: true
    Range: 25
  Empire Blink:
    Enabled: true
    Range: 15
  Empire Cloud:
    Enabled: true
  Empire Comet:
    Enabled: true
  Empire Confuse:
    Enabled: true
    Range: 25
  Empire Spark:
    Enabled: true
    Range: 25
  Empire Stun:
    Enabled: true
    Range: 25
  Fireball:
    Enabled: true
  Fire Pulse:
    Enabled: true
  Flame Wave:
    Enabled: true
  Ignite:
    Enabled: true
    Range: 25
  Launch:
    Enabled: true
    Range: 25
  Lightning:
    Enabled: true
  Poison Cloud:
    Enabled: true
  Poison Spark:
    Enabled: true
    Range: 25
  Poison Wave:
    Enabled: true
  Smite:
    Enabled: true